 
version: '2'
services:
  convert:
    image: tomcat
    ports: 
      - "8080:8080"
    volumes:
      - ./lib/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./lib/manager.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml
      - ./lib/docroot:/usr/local/tomcat/docroot
      - ./target/microservice-example.war:/usr/local/tomcat/webapps/microservice-example.war
      - ./target/microservice-example:/usr/local/tomcat/webapps/microservice-example
